export function timeAgo(timestamp: number): string {
  const now = new Date().getTime();
  const diffInSeconds = Math.floor((now - timestamp) / 1000);

  if (diffInSeconds < 60) return `${diffInSeconds} seconds ago`;
  const diffInMinutes = Math.floor(diffInSeconds / 60);
  if (diffInMinutes < 60) return `${diffInMinutes} min ago`;
  const diffInHours = Math.floor(diffInMinutes / 60);
  if (diffInHours < 24) return `${diffInHours} hrs ago`;
  const diffInDays = Math.floor(diffInHours / 24);
  return `${diffInDays} d ago`;
}

export const mockNewsData = [
  // Amit Sharma
  {
    headline: 'Apple’s AI Push: A New Era for Growth',
    summary: 'Apple unveils a major AI initiative, integrating generative AI into Siri and iOS. The move is expected to drive user engagement and open new revenue streams.',
    tip: 'Apple’s surprise AI announcement is expected to spark a new growth cycle and investor optimism.',
    symbol: 'AAPL',
    compareSymbol: 'MSFT',
    user: { name: 'Amit Sharma', avatar: 'https://randomuser.me/api/portraits/men/32.jpg' },
    timestamp: new Date().getTime() - 3 * 60 * 60 * 1000,
    entryPrice: '$185–$188',
    stopLoss: '$175',
    targetDuration: '6–12 months',
    allocation: '12%',
    catalyst: 'AI product launch, earnings',
    valuation: 'P/E 28x, DCF +10%',
    sentiment: 'Bullish',
    technical: 'RSI 62, MA bullish crossover',
    confidence: '85%',
    diversification: 'Core holding',
    liquidity: 'High',
    expectedReturn: '18%',
    performance: '72%',
    sector: 'Technology',
  },
  {
    headline: 'Apple Services Surge: The Next Growth Engine',
    summary: 'Apple’s services division posts record revenue, driven by App Store and Apple Music. Recurring revenue is becoming a key profit driver.',
    tip: 'Record-breaking services revenue signals a shift in Apple’s business model and future profit drivers.',
    symbol: 'AAPL',
    compareSymbol: 'GOOGL',
    user: { name: 'Amit Sharma', avatar: 'https://randomuser.me/api/portraits/men/32.jpg' },
    timestamp: new Date().getTime() - 7 * 60 * 60 * 1000,
    entryPrice: '$182–$186',
    stopLoss: '$170',
    targetDuration: '12 months',
    allocation: '10%',
    catalyst: 'Services revenue, App Store growth',
    valuation: 'P/E 27x, EV/EBITDA 21x',
    sentiment: 'Bullish',
    technical: 'MACD bullish, RSI 59',
    confidence: '80%',
    diversification: 'Core holding',
    liquidity: 'High',
    expectedReturn: '15%',
    performance: '70%',
    sector: 'Technology',
  },

  // Nitya Singh
  {
    headline: 'Ethereum ETF Approval: Institutional Demand Rises',
    summary: 'The SEC approves the first Ethereum ETF, opening the door for institutional inflows. DeFi and staking activity remain strong.',
    tip: 'The SEC’s approval of an Ethereum ETF is a game-changer, unlocking new institutional demand.',
    symbol: 'ETH-USD',
    compareSymbol: 'BTC-USD',
    user: { name: 'Nitya Singh', avatar: 'https://randomuser.me/api/portraits/women/44.jpg' },
    timestamp: new Date().getTime() - 5 * 60 * 60 * 1000,
    entryPrice: '$3,400–$3,520',
    stopLoss: '$3,200',
    targetDuration: '3–6 months',
    allocation: '8%',
    catalyst: 'ETF approval, DeFi growth',
    valuation: 'EV/EBITDA 15x, DCF +12%',
    sentiment: 'Bullish',
    technical: 'RSI 65, MA bullish',
    confidence: '78%',
    diversification: 'Satellite',
    liquidity: 'High',
    expectedReturn: '22%',
    performance: '68%',
    sector: 'Crypto',
  },
  {
    headline: 'Ethereum Network Upgrade: Scalability & Growth',
    summary: 'Ethereum completes a major upgrade, reducing fees and boosting scalability. This is expected to attract more users and developers.',
    tip: 'Major network upgrade positions Ethereum for the next wave of DeFi and developer adoption.',
    symbol: 'ETH-USD',
    compareSymbol: 'SOL-USD',
    user: { name: 'Nitya Singh', avatar: 'https://randomuser.me/api/portraits/women/44.jpg' },
    timestamp: new Date().getTime() - 8 * 60 * 60 * 1000,
    entryPrice: '$3,300–$3,450',
    stopLoss: '$3,100',
    targetDuration: '6 months',
    allocation: '7%',
    catalyst: 'Network upgrade, DeFi',
    valuation: 'P/E 20x, DCF +14%',
    sentiment: 'Bullish',
    technical: 'MACD bullish, RSI 63',
    confidence: '75%',
    diversification: 'Satellite',
    liquidity: 'High',
    expectedReturn: '19%',
    performance: '65%',
    sector: 'Crypto',
  },

  // John Lee
  {
    headline: 'Gold ETF Inflows Surge: Safe Haven Demand',
    summary: 'Gold-backed ETFs see record inflows as investors seek safety amid global uncertainty. Central bank buying remains strong.',
    tip: 'Surging ETF inflows highlight gold’s renewed appeal as a safe haven during global uncertainty.',
    symbol: 'XAUUSD',
    compareSymbol: 'USD',
    user: { name: 'John Lee', avatar: 'https://randomuser.me/api/portraits/men/65.jpg' },
    timestamp: new Date().getTime() - 6 * 60 * 60 * 1000,
    entryPrice: '$2,300–$2,320',
    stopLoss: '$2,200',
    targetDuration: '6 months',
    allocation: '6%',
    catalyst: 'ETF inflows, central bank demand',
    valuation: 'P/E 16x, DCF +8%',
    sentiment: 'Bullish',
    technical: 'RSI 58, MA bullish',
    confidence: '72%',
    diversification: 'Hedge',
    liquidity: 'High',
    expectedReturn: '12%',
    performance: '60%',
    sector: 'Commodities',
  },
  {
    headline: 'Gold Faces Fed Headwinds: Volatility Ahead',
    summary: 'Gold prices drop as Fed signals more rate hikes. However, Indian demand and central bank buying provide support.',
    tip: 'Fed’s hawkish stance triggers volatility, but underlying demand may cushion gold’s downside.',
    symbol: 'XAUUSD',
    compareSymbol: 'INR',
    user: { name: 'John Lee', avatar: 'https://randomuser.me/api/portraits/men/65.jpg' },
    timestamp: new Date().getTime() - 10 * 60 * 60 * 1000,
    entryPrice: '$2,320–$2,340',
    stopLoss: '$2,400',
    targetDuration: '3 months',
    allocation: '5%',
    catalyst: 'Fed policy, Indian demand',
    valuation: 'EV/EBITDA 10x',
    sentiment: 'Bearish',
    technical: 'MACD bearish, RSI 48',
    confidence: '65%',
    diversification: 'Hedge',
    liquidity: 'High',
    expectedReturn: '7%',
    performance: '58%',
    sector: 'Commodities',
  },

  // Sara Tanaka
  {
    headline: 'USD/JPY Surges: BOJ Policy Divergence',
    summary: 'The US dollar hits 150 yen as the Bank of Japan maintains ultra-loose policy. US-Japan rate differentials drive the move.',
    tip: 'BOJ’s continued dovish policy is fueling a sharp move in USD/JPY, creating a trading opportunity.',
    symbol: 'USDJPY',
    compareSymbol: 'EURJPY',
    user: { name: 'Sara Tanaka', avatar: 'https://randomuser.me/api/portraits/women/68.jpg' },
    timestamp: new Date().getTime() - 4 * 60 * 60 * 1000,
    entryPrice: '149.5–150.5',
    stopLoss: '147',
    targetDuration: '6 months',
    allocation: '9%',
    catalyst: 'BOJ policy, US rates',
    valuation: 'P/E 14x',
    sentiment: 'Bullish',
    technical: 'RSI 70, MA bullish',
    confidence: '77%',
    diversification: 'Core holding',
    liquidity: 'High',
    expectedReturn: '14%',
    performance: '66%',
    sector: 'FX',
  },
  {
    headline: 'Yen Volatility: Intervention Rumors Swirl',
    summary: 'Rumors of BOJ intervention spark volatility in the yen. Traders watch for policy signals and macro data.',
    tip: 'Speculation around BOJ intervention is driving short-term volatility and tactical trading setups.',
    symbol: 'USDJPY',
    compareSymbol: 'JPY=X',
    user: { name: 'Sara Tanaka', avatar: 'https://randomuser.me/api/portraits/women/68.jpg' },
    timestamp: new Date().getTime() - 9 * 60 * 60 * 1000,
    entryPrice: '148–150',
    stopLoss: '146',
    targetDuration: '1–2 months',
    allocation: '6%',
    catalyst: 'BOJ intervention rumors',
    valuation: 'P/E 13x',
    sentiment: 'Neutral',
    technical: 'MACD neutral, RSI 52',
    confidence: '60%',
    diversification: 'Satellite',
    liquidity: 'High',
    expectedReturn: '6%',
    performance: '62%',
    sector: 'FX',
  },
];
     

