export const mockNewsData = [
  // Nitya
  {
    headline: 'Trump Threatens 60% Tariffs on EU BMW, Mercedes Imports',
    summary: 'Trump proposes a 60% tariff on BMW and Mercedes imports from the EU, escalating trade tensions. This could raise prices and disrupt supply chains.',
    tip: 'Short BMW.DE. Tariffs may reduce US sales and pressure the stock in the near term.',
    symbol: 'BMW.DE',
    compareSymbol: 'DDAIF',
    user: { name: 'Nitya', avatar: 'https://hpoornsnjpjjjvurwjle.supabase.co/storage/v1/object/public/post-images/1750378633414_p.JPG' },
  },
  {
    headline: 'BMW Faces Supply Chain Disruptions in Europe',
    summary: 'BMW faces delays in parts shipments due to new EU regulations, slowing production at several plants and impacting Q3 output for the company.',
    tip: 'Monitor BMW.DE for volatility as supply chain issues persist. Regulatory changes may impact performance.',
    symbol: 'BMW.DE',
    compareSymbol: 'VOW3.DE',
    user: { name: 'Nitya', avatar: 'https://hpoornsnjpjjjvurwjle.supabase.co/storage/v1/object/public/post-images/1750378633414_p.JPG' },
  },
  {
    headline: 'BMW Launches New Electric SUV',
    summary: 'BMW unveils a new electric SUV for the US and China. Early reviews are positive, and pre-orders are strong, boosting their position in the EV market.',
    tip: 'Long BMW.DE as EV segment growth accelerates. Watch for strong sales in key regions.',
    symbol: 'BMW.DE',
    compareSymbol: 'TSLA',
    user: { name: 'Nitya', avatar: 'https://hpoornsnjpjjjvurwjle.supabase.co/storage/v1/object/public/post-images/1750378633414_p.JPG' },
  },
  {
    headline: 'BMW Reports Record Q2 Profits',
    summary: 'BMW posted record Q2 profits, driven by strong demand in Asia and higher margins on luxury models. The company expects earnings momentum to continue.',
    tip: 'Buy BMW.DE on earnings momentum. Strong results support further upside.',
    symbol: 'BMW.DE',
    compareSymbol: 'DDAIF',
    user: { name: 'Nitya', avatar: 'https://hpoornsnjpjjjvurwjle.supabase.co/storage/v1/object/public/post-images/1750378633414_p.JPG' },
  },
  {
    headline: 'BMW Expands Partnership with Google for In-Car Tech',
    summary: 'BMW and Google expand their partnership to integrate Google services into BMW’s next-gen infotainment systems, enhancing brand value.',
    tip: 'Positive for BMW.DE as tech partnerships enhance brand value and user experience.',
    symbol: 'BMW.DE',
    compareSymbol: 'GOOGL',
    user: { name: 'Nitya', avatar: 'https://hpoornsnjpjjjvurwjle.supabase.co/storage/v1/object/public/post-images/1750378633414_p.JPG' },
  },

  // Amit Sharma
  {
    headline: 'Apple Stock Surges After Strong Q2 Earnings',
    summary: 'Apple reported record Q2 earnings, beating expectations. iPhone sales led growth, especially in Asia. The company also announced a new buyback and higher dividends for shareholders.',
    tip: 'Buy AAPL. Strong earnings and buyback could drive upside.',
    symbol: 'AAPL',
    compareSymbol: 'MSFT',
    user: { name: 'Amit Sharma', avatar: 'https://randomuser.me/api/portraits/men/32.jpg' },
  },
  {
    headline: 'Apple Unveils New iPhone Model',
    summary: 'Apple announced its latest iPhone with better battery life and camera. Pre-orders are strong, showing high demand for the new model among consumers.',
    tip: 'AAPL may rally on new product excitement.',
    symbol: 'AAPL',
    compareSymbol: 'GOOGL',
    user: { name: 'Amit Sharma', avatar: 'https://randomuser.me/api/portraits/men/32.jpg' },
  },
  {
    headline: 'Apple Expands Services Revenue',
    summary: 'Apple’s services division is growing fast, with App Store and Apple Music revenues reaching new highs. Services are a key profit driver.',
    tip: 'Long AAPL for continued services growth.',
    symbol: 'AAPL',
    compareSymbol: 'AMZN',
    user: { name: 'Amit Sharma', avatar: 'https://randomuser.me/api/portraits/men/32.jpg' },
  },
  {
    headline: 'Apple Faces Regulatory Scrutiny in EU',
    summary: 'The EU is investigating Apple’s App Store practices. This could lead to fines or changes in how Apple operates in Europe.',
    tip: 'Watch AAPL for volatility as regulatory risks rise.',
    symbol: 'AAPL',
    compareSymbol: 'MSFT',
    user: { name: 'Amit Sharma', avatar: 'https://randomuser.me/api/portraits/men/32.jpg' },
  },
  {
    headline: 'Apple Announces Major AI Initiative',
    summary: 'Apple is investing in AI, with new features planned for Siri and iOS. Analysts see this as a key growth driver for the company.',
    tip: 'Positive for AAPL as AI becomes a core focus.',
    symbol: 'AAPL',
    compareSymbol: 'GOOGL',
    user: { name: 'Amit Sharma', avatar: 'https://randomuser.me/api/portraits/men/32.jpg' },
  },

  // Priya Singh
  {
    headline: 'Ethereum Breaks $3,500 as Crypto Rally Continues',
    summary: 'Ethereum (ETH) surged past $3,500, driven by DeFi activity and institutional interest. Further gains are possible if Bitcoin stays above $60,000.',
    tip: 'Buy ETH (ETH-USD, LTP: $3,520). Momentum and institutional interest could push prices higher.',
    symbol: 'ETH-USD',
    compareSymbol: 'BTC-USD',
    user: { name: 'Priya Singh', avatar: 'https://randomuser.me/api/portraits/women/44.jpg' },
  },
  {
    headline: 'Ethereum Network Upgrade Completed',
    summary: 'Ethereum completed a major upgrade, lowering transaction fees and improving scalability. This could attract more users and boost network activity.',
    tip: 'Bullish for ETH-USD as network improvements attract more users.',
    symbol: 'ETH-USD',
    compareSymbol: 'SOL-USD',
    user: { name: 'Priya Singh', avatar: 'https://randomuser.me/api/portraits/women/44.jpg' },
  },
  {
    headline: 'Ethereum ETF Approved in US',
    summary: 'The SEC approved the first Ethereum ETF in the US, allowing institutional investors to gain exposure. This could increase demand for ETH.',
    tip: 'ETH-USD could see inflows from new ETF products.',
    symbol: 'ETH-USD',
    compareSymbol: 'BTC-USD',
    user: { name: 'Priya Singh', avatar: 'https://randomuser.me/api/portraits/women/44.jpg' },
  },
  {
    headline: 'DeFi Activity on Ethereum Hits Record High',
    summary: 'DeFi activity on Ethereum reached new highs, with total value locked surpassing $100B. This growth highlights Ethereum’s leading role in decentralized finance.',
    tip: 'ETH-USD benefits from DeFi growth.',
    symbol: 'ETH-USD',
    compareSymbol: 'UNI-USD',
    user: { name: 'Priya Singh', avatar: 'https://randomuser.me/api/portraits/women/44.jpg' },
  },
  {
    headline: 'Ethereum Developers Plan Next Upgrade',
    summary: 'Ethereum developers announced the next major upgrade, focusing on security and speed. The community expects further improvements to the network’s performance.',
    tip: 'Watch ETH-USD for volatility around upgrade events.',
    symbol: 'ETH-USD',
    compareSymbol: 'BTC-USD',
    user: { name: 'Priya Singh', avatar: 'https://randomuser.me/api/portraits/women/44.jpg' },
  },

  // John Lee
  {
    headline: 'Gold Prices Drop Amid Fed Rate Hike Speculation',
    summary: 'Gold prices fell as investors expect more US Fed rate hikes. Higher yields and a stronger dollar are putting pressure on precious metals.',
    tip: 'Short Gold (XAUUSD, LTP: $2,320). Higher rates and strong dollar may pressure gold prices.',
    symbol: 'XAUUSD',
    compareSymbol: 'USD',
    user: { name: 'John Lee', avatar: 'https://randomuser.me/api/portraits/men/65.jpg' },
  },
  {
    headline: 'Gold Demand Rises in India',
    summary: 'Gold demand in India has increased ahead of the festival season, helping support global prices even as US factors weigh on the market.',
    tip: 'Monitor XAUUSD for support above $2,300.',
    symbol: 'XAUUSD',
    compareSymbol: 'INR',
    user: { name: 'John Lee', avatar: 'https://randomuser.me/api/portraits/men/65.jpg' },
  },
  {
    headline: 'Central Banks Increase Gold Reserves',
    summary: 'Central banks are increasing gold reserves due to economic uncertainty and inflation concerns. This trend could support gold prices in the coming months.',
    tip: 'Long XAUUSD as central bank demand grows.',
    symbol: 'XAUUSD',
    compareSymbol: 'USD',
    user: { name: 'John Lee', avatar: 'https://randomuser.me/api/portraits/men/65.jpg' },
  },
  {
    headline: 'Gold ETF Inflows Surge',
    summary: 'Gold-backed ETFs have seen a surge in inflows as investors seek safe-haven assets. This demand could help support gold prices going forward.',
    tip: 'ETF demand could support XAUUSD prices.',
    symbol: 'XAUUSD',
    compareSymbol: 'USD',
    user: { name: 'John Lee', avatar: 'https://randomuser.me/api/portraits/men/65.jpg' },
  },
  {
    headline: 'Gold Mining Costs Rise',
    summary: 'Rising energy and labor costs are pushing up gold mining expenses, which could impact supply and influence prices in the market.',
    tip: 'Watch XAUUSD for supply-driven price moves.',
    symbol: 'XAUUSD',
    compareSymbol: 'USD',
    user: { name: 'John Lee', avatar: 'https://randomuser.me/api/portraits/men/65.jpg' },
  },

  // Sara Tanaka
  {
    headline: 'USD/JPY Hits 150 As Yen Weakens',
    summary: 'The US dollar hit 150 yen, reaching its highest level in years as the Bank of Japan continues its ultra-loose monetary policy. This significant milestone reflects ongoing divergence between US and Japanese interest rates, with the Federal Reserve maintaining a much tighter stance. Many traders believe the yen will remain weak unless the Bank of Japan signals a shift in policy. Market participants are closely watching for any signs of intervention or policy change that could alter the current trend, as even small signals can move the currency markets dramatically.',
    tip: 'Buy USD/JPY (USDJPY, LTP: 150.12). BOJ policy and US rate differentials favor dollar strength.',
    symbol: 'USDJPY',
    compareSymbol: 'EURJPY',
    user: { name: 'Sara Tanaka', avatar: 'https://randomuser.me/api/portraits/women/68.jpg' },
  },
  {
    headline: 'Yen Intervention Rumors Swirl',
    summary: 'Rumors of possible intervention by the Bank of Japan have led to increased volatility in the yen, as traders and investors react to speculation about potential government action. The currency markets are highly sensitive to any hints of intervention, and even unconfirmed reports can trigger significant price swings. Market participants are monitoring official statements and economic data for clues about the likelihood and timing of any intervention. In the past, such rumors have sometimes preceded actual moves by the central bank, so traders are especially alert to any new developments or policy signals.',
    tip: 'Expect USDJPY swings on intervention headlines.',
    symbol: 'USDJPY',
    compareSymbol: 'JPY=X',
    user: { name: 'Sara Tanaka', avatar: 'https://randomuser.me/api/portraits/women/68.jpg' },
  },
  {
    headline: 'Japan Maintains Negative Interest Rates',
    summary: 'The Bank of Japan has decided to maintain its negative interest rate policy, citing persistent low inflation and sluggish economic growth as key reasons. This ongoing stance is intended to stimulate the economy but has also contributed to continued weakness in the yen. Investors are watching for any changes in the central bank’s outlook, as a shift could have significant implications for currency and financial markets. The policy has been in place for years, and while it supports lending and investment, it also discourages foreign capital inflows, keeping the yen under pressure.',
    tip: 'USDJPY may remain strong as rate differentials persist.',
    symbol: 'USDJPY',
    compareSymbol: 'EURJPY',
    user: { name: 'Sara Tanaka', avatar: 'https://randomuser.me/api/portraits/women/68.jpg' },
  },
  {
    headline: 'Japanese Exports Beat Expectations',
    summary: 'Japan’s exports have exceeded market expectations, providing the yen with some short-term support despite the Bank of Japan’s ongoing accommodative monetary policy. Strong export performance is seen as a positive sign for the Japanese economy, especially in key sectors like automobiles and electronics. However, many analysts believe that the overall trend for the yen remains weak as long as the central bank maintains its current stance. Market participants are watching for further economic data and policy signals, as sustained export growth could eventually influence monetary policy decisions.',
    tip: 'Short-term support for JPY, but trend remains weak.',
    symbol: 'USDJPY',
    compareSymbol: 'EURJPY',
    user: { name: 'Sara Tanaka', avatar: 'https://randomuser.me/api/portraits/women/68.jpg' },
  },
  {
    headline: 'US-Japan Trade Talks Resume',
    summary: 'Trade talks between the US and Japan have resumed, with currency policy emerging as a central topic of discussion. Both countries are seeking to address trade imbalances and concerns about exchange rate movements, which have been a source of tension in the past. Market participants are closely monitoring the negotiations for any signs of progress or setbacks, as outcomes could have significant implications for the yen and broader financial markets. Any new developments are likely to influence investor sentiment and trading activity, especially if agreements are reached on currency stabilization or intervention measures.',
    tip: 'USDJPY could react to trade headlines.',
    symbol: 'USDJPY',
    compareSymbol: 'EURJPY',
    user: { name: 'Sara Tanaka', avatar: 'https://randomuser.me/api/portraits/women/68.jpg' },
  },
];
