export const mockNewsData = [

 // Asset Class: Derivatives

 {
 id: 2,
 name: "Bob",
 avatar: "https://randomuser.me/api/portraits/men/2.jpg",
 asset_type: "Derivatives",
 sector: "Technology",
 tip: "Hedge your tech portfolio with Nasdaq futures.\nIndex nearing all-time highs signals potential corrections.",
 symbol: "NDX",
 created_at: "2025-07-25T11:00:00Z", // 22 July 11am
 entry_price: 22500,
 exit_price: 22200,
 target_duration: "2 days",
 allocation: "10%",
 catalyst: "Upcoming RBI policy",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "RSI above 60, MACD bullish",
 confidence: "High",
 diversification: "Fits with equity exposure",
 liquidity: "High",
 expected_return: "8%",
 performance: "Last 3 tips: +7%, +5%, +9%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Momentum"
 },

 {
 id: 3,
 name: "Carol",
 avatar: "https://randomuser.me/api/portraits/women/3.jpg",
 asset_type: "Derivatives",
 sector: "Energy",
 tip: "Use crude oil options to manage risk.\nEnergy prices are volatile due to supply concerns.",
 symbol: "CL",
 created_at: "2025-07-22T11:00:00Z", // 22 July 11am
 entry_price: 80,
 exit_price: 78,
 target_duration: "3 days",
 allocation: "8%",
 catalyst: "OPEC meeting",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "RSI above 70, bearish divergence",
 confidence: "Moderate",
 diversification: "Complements energy exposure",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +4%, -2%, +6%",
 holding: "Sell",
 risk: "High",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Hedging"
 },

 {
 id: 4,
 name: "Dave",
 avatar: "https://randomuser.me/api/portraits/men/4.jpg",
 asset_type: "Derivatives",
 sector: "Healthcare",
 tip: "Protect pharma stocks with put options.\nSector faces regulatory risks this quarter.",
 symbol: "PFE",
 created_at: "2025-07-22T11:00:00Z", // 22 July 11am
 entry_price: 45,
 exit_price: 43,
 target_duration: "1 week",
 allocation: "7%",
 catalyst: "FDA announcements",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "MACD bearish crossover",
 confidence: "Moderate",
 diversification: "Balances healthcare exposure",
 liquidity: "Medium",
 expected_return: "5%",
 performance: "Last 3 tips: +3%, +4%, -1%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "65%",
 strategy: "Risk Management"
 },

 {
 id: 30,
 name: "Edward",
 avatar: "https://randomuser.me/api/portraits/men/30.jpg",
 asset_type: "Derivatives",
 sector: "Technology",
 tip: "Leverage MSFT futures for potential gains.\nUpcoming events may shift prices.",
 symbol: "MSFT",
 created_at: "2025-06-26T15:00:00Z",
 entry_price: 917.48,
 exit_price: 964.81,
 target_duration: "1 day",
 allocation: "15%",
 catalyst: "Sector growth",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "50DMA support",
 confidence: "Low",
 diversification: "Mitigates risk",
 liquidity: "High",
 expected_return: "7%",
 performance: "Last 3 tips: +9%, +7%, +6%",
 holding: "Hold",
 risk: "Low",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Momentum"
 },
 {
 id: 31,
 name: "Amy",
 avatar: "https://randomuser.me/api/portraits/women/31.jpg",
 asset_type: "Derivatives",
 sector: "Technology",
 tip: "Consider FTSE futures to hedge Technology risks.\nTraders expect swings soon.",
 symbol: "FTSE",
 created_at: "2025-06-25T16:00:00Z",
 entry_price: 1024.37,
 exit_price: 987.21,
 target_duration: "2 weeks",
 allocation: "10%",
 catalyst: "Regulatory news",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "MACD bullish crossover",
 confidence: "Moderate",
 diversification: "Diversifies exposure",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +4%, +6%, +2%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Hedging"
 },
 {
 id: 32,
 name: "Brandon",
 avatar: "https://randomuser.me/api/portraits/men/32.jpg",
 asset_type: "Derivatives",
 sector: "Energy",
 tip: "Consider AMD futures for Energy exposure.\nTraders expect swings soon.",
 symbol: "AMD",
 created_at: "2025-06-24T17:00:00Z",
 entry_price: 95.12,
 exit_price: 89.54,
 target_duration: "1 week",
 allocation: "12%",
 catalyst: "Monetary policy",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "RSI below 37",
 confidence: "Moderate",
 diversification: "Reduces portfolio volatility",
 liquidity: "Medium",
 expected_return: "5%",
 performance: "Last 3 tips: +3%, +6%, +0%",
 holding: "Sell",
 risk: "High",
 conviction: "Medium",
 win_rate: "60%",
 strategy: "Risk Management"
 },
 {
 id: 33,
 name: "Deborah",
 avatar: "https://randomuser.me/api/portraits/women/33.jpg",
 asset_type: "Derivatives",
 sector: "Energy",
 tip: "Use NG futures to hedge Energy risks.\nMarket volatility suggests caution.",
 symbol: "NG",
 created_at: "2025-06-23T18:00:00Z",
 entry_price: 905.94,
 exit_price: 893.92,
 target_duration: "6 months",
 allocation: "15%",
 catalyst: "New technology development",
 valuation: "Fair",
 sentiment: "Bearish",
 technical: "RSI below 29",
 confidence: "High",
 diversification: "Diversifies exposure",
 liquidity: "Very High",
 expected_return: "4%",
 performance: "Last 3 tips: +10%, +4%, -4%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Long-Term Growth"
 },
 {
 id: 34,
 name: "Stephen",
 avatar: "https://randomuser.me/api/portraits/men/34.jpg",
 asset_type: "Derivatives",
 sector: "Healthcare",
 tip: "Protect your portfolio with NFLX futures.\nTraders expect swings soon.",
 symbol: "NFLX",
 created_at: "2025-06-22T19:00:00Z",
 entry_price: 351.97,
 exit_price: 373.25,
 target_duration: "2 weeks",
 allocation: "9%",
 catalyst: "Sector growth",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "MACD turning up",
 confidence: "High",
 diversification: "Reduces volatility",
 liquidity: "Very High",
 expected_return: "9%",
 performance: "Last 3 tips: +10%, +7%, +1%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Momentum"
 },
 {
 id: 35,
 name: "Brianna",
 avatar: "https://randomuser.me/api/portraits/women/35.jpg",
 asset_type: "Derivatives",
 sector: "Healthcare",
 tip: "Protect your portfolio with VIX futures.\nMarket volatility suggests caution.",
 symbol: "VIX",
 created_at: "2025-06-21T20:00:00Z",
 entry_price: 327.76,
 exit_price: 316.60,
 target_duration: "3 days",
 allocation: "9%",
 catalyst: "Sector growth",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Bollinger Bands widening",
 confidence: "Low",
 diversification: "Complements fixed income exposure",
 liquidity: "Very High",
 expected_return: "9%",
 performance: "Last 3 tips: +0%, +9%, +8%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "74%",
 strategy: "Speculative"
 },
 {
 id: 36,
 name: "Charles",
 avatar: "https://randomuser.me/api/portraits/men/36.jpg",
 asset_type: "Derivatives",
 sector: "Financials",
 tip: "Protect your portfolio with ES futures.\nMarket volatility suggests caution.",
 symbol: "ES",
 created_at: "2025-06-20T21:00:00Z",
 entry_price: 478.33,
 exit_price: 465.12,
 target_duration: "1 month",
 allocation: "10%",
 catalyst: "Economic data release",
 valuation: "Fair",
 sentiment: "Bearish",
 technical: "50DMA resistance",
 confidence: "Moderate",
 diversification: "Fits with overall strategy",
 liquidity: "High",
 expected_return: "7%",
 performance: "Last 3 tips: +8%, -2%, +5%",
 holding: "Sell",
 risk: "High",
 conviction: "Medium",
 win_rate: "68%",
 strategy: "Risk Management"
 },
 {
 id: 37,
 name: "Donna",
 avatar: "https://randomuser.me/api/portraits/women/37.jpg",
 asset_type: "Derivatives",
 sector: "Financials",
 tip: "Use GC futures to hedge Financials risks.\nMarket volatility suggests caution.",
 symbol: "GC",
 created_at: "2025-06-19T22:00:00Z",
 entry_price: 2051.28,
 exit_price: 1987.65,
 target_duration: "3 months",
 allocation: "11%",
 catalyst: "Federal Reserve policy",
 valuation: "Overvalued",
 sentiment: "Neutral",
 technical: "RSI at 42",
 confidence: "High",
 diversification: "Reduces portfolio volatility",
 liquidity: "Medium",
 expected_return: "5%",
 performance: "Last 3 tips: +7%, +2%, +6%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },
 {
 id: 38,
 name: "Ellen",
 avatar: "https://randomuser.me/api/portraits/women/38.jpg",
 asset_type: "Derivatives",
 sector: "Technology",
 tip: "Consider SIL futures for Technology exposure.\nMarket volatility suggests caution.",
 symbol: "SIL",
 created_at: "2025-06-18T23:00:00Z",
 entry_price: 34.78,
 exit_price: 36.12,
 target_duration: "6 months",
 allocation: "13%",
 catalyst: "Interest rate decision",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "Moving average bullish crossover",
 confidence: "Moderate",
 diversification: "Diversifies exposure",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +4%, +5%, +7%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "78%",
 strategy: "Long-Term Growth"
 },
 {
 id: 39,
 name: "Patricia",
 avatar: "https://randomuser.me/api/portraits/women/39.jpg",
 asset_type: "Derivatives",
 sector: "Energy",
 tip: "Protect your portfolio with TSLA futures.\nMarket volatility suggests caution.",
 symbol: "TSLA",
 created_at: "2025-06-17T00:00:00Z",
 entry_price: 630.68,
 exit_price: 613.54,
 target_duration: "2 days",
 allocation: "20%",
 catalyst: "Economic data release",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "50DMA support",
 confidence: "Moderate",
 diversification: "Complements equity exposure",
 liquidity: "Very High",
 expected_return: "9%",
 performance: "Last 3 tips: -5%, +1%, -5%",
 holding: "Sell",
 risk: "Medium",
 conviction: "Weak",
 win_rate: "80%",
 strategy: "Passive Indexing"
 },

 // Asset Class: Indexes

 {
 id: 5,
 name: "Eve",
 avatar: "https://randomuser.me/api/portraits/women/5.jpg",
 asset_type: "Indexes",
 sector: "Technology",
 tip: "Track S&P 500 for broad market exposure.\nTech earnings may drive index performance.",
 symbol: "SPX",
 created_at: "2025-07-21T14:00:00Z",
 entry_price: 5550,
 exit_price: 5400,
 target_duration: "1 week",
 allocation: "15%",
 catalyst: "Tech earnings season",
 valuation: "Undervalued",
 sentiment: "Neutral",
 technical: "50DMA support",
 confidence: "Moderate",
 diversification: "Balances sector risk",
 liquidity: "Very High",
 expected_return: "5%",
 performance: "Index up 12% YTD",
 holding: "Hold",
 risk: "Low",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Passive Indexing"
 },

 {
 id: 6,
 name: "Frank",
 avatar: "https://randomuser.me/api/portraits/men/6.jpg",
 asset_type: "Indexes",
 sector: "Financials",
 tip: "Monitor Bank Nifty for financial trends.\nBanking sector shows strong Q2 earnings.",
 symbol: "BANKNIFTY",
 created_at: "2025-07-20T15:00:00Z",
 entry_price: 48000,
 exit_price: 47000,
 target_duration: "1 month",
 allocation: "12%",
 catalyst: "RBI rate decision",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "RSI above 55, bullish trend",
 confidence: "High",
 diversification: "Complements equity portfolio",
 liquidity: "High",
 expected_return: "7%",
 performance: "Index up 10% YTD",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Trend Following"
 },

 {
 id: 7,
 name: "Grace",
 avatar: "https://randomuser.me/api/portraits/women/7.jpg",
 asset_type: "Indexes",
 sector: "Energy",
 tip: "Energy index shows bullish momentum.\nOil price trends support sector growth.",
 symbol: "IXE",
 created_at: "2025-07-19T16:00:00Z",
 entry_price: 650,
 exit_price: 620,
 target_duration: "2 weeks",
 allocation: "10%",
 catalyst: "Geopolitical tensions",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "Moderate",
 diversification: "Balances commodity exposure",
 liquidity: "Medium",
 expected_return: "6%",
 performance: "Index up 8% YTD",
 holding: "Buy",
 risk: "High",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Momentum"
 },

 {
 id: 8,
 name: "Henry",
 avatar: "https://randomuser.me/api/portraits/men/8.jpg",
 asset_type: "Indexes",
 sector: "Healthcare",
 tip: "Healthcare index outperforms in Q2.\nStrong R&D pipelines drive growth.",
 symbol: "IXHC",
 created_at: "2025-07-18T17:00:00Z",
 entry_price: 1200,
 exit_price: 1150,
 target_duration: "3 weeks",
 allocation: "9%",
 catalyst: "New drug approvals",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "50DMA resistance",
 confidence: "Moderate",
 diversification: "Reduces sector risk",
 liquidity: "High",
 expected_return: "5%",
 performance: "Index up 9% YTD",
 holding: "Hold",
 risk: "Low",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Value Investing"
 },

 {
 id: 40,
 name: "Evan",
 avatar: "https://randomuser.me/api/portraits/men/40.jpg",
 asset_type: "Indexes",
 sector: "Technology",
 tip: "Follow DAX to gauge market momentum.\nSector performances will play a role.",
 symbol: "DAX",
 created_at: "2025-06-16T01:00:00Z",
 entry_price: 585.59,
 exit_price: 532.19,
 target_duration: "3 months",
 allocation: "12%",
 catalyst: "Sector growth",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "High",
 diversification: "Balances sector risk",
 liquidity: "High",
 expected_return: "10%",
 performance: "Index up 14% YTD",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "82%",
 strategy: "Value Investing"
 },
 {
 id: 41,
 name: "Fiona",
 avatar: "https://randomuser.me/api/portraits/women/41.jpg",
 asset_type: "Indexes",
 sector: "Technology",
 tip: "Track DJI for broad market exposure.\nEconomic data or earnings may shift it.",
 symbol: "DJI",
 created_at: "2025-06-15T02:00:00Z",
 entry_price: 33000,
 exit_price: 32500,
 target_duration: "6 months",
 allocation: "14%",
 catalyst: "Economic data release",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "50DMA support",
 confidence: "Moderate",
 diversification: "Diversifies exposure",
 liquidity: "Very High",
 expected_return: "6%",
 performance: "Index up 15% YTD",
 holding: "Hold",
 risk: "Low",
 conviction: "Medium",
 win_rate: "76%",
 strategy: "Long-Term Growth"
 },
 {
 id: 42,
 name: "George",
 avatar: "https://randomuser.me/api/portraits/men/42.jpg",
 asset_type: "Indexes",
 sector: "Energy",
 tip: "Track SENSEX for broad market exposure.\nTrade data might influence movement.",
 symbol: "SENSEX",
 created_at: "2025-06-14T03:00:00Z",
 entry_price: 51000,
 exit_price: 49500,
 target_duration: "1 month",
 allocation: "13%",
 catalyst: "Geopolitical event",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "RSI above 65",
 confidence: "High",
 diversification: "Complements portfolio",
 liquidity: "High",
 expected_return: "5%",
 performance: "Index up 11% YTD",
 holding: "Sell",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Trend Following"
 },
 {
 id: 43,
 name: "Hannah",
 avatar: "https://randomuser.me/api/portraits/women/43.jpg",
 asset_type: "Indexes",
 sector: "Energy",
 tip: "Monitor IXHC as Energy trends evolve.\nSector performances will play a role.",
 symbol: "IXHC",
 created_at: "2025-06-13T04:00:00Z",
 entry_price: 2300,
 exit_price: 2250,
 target_duration: "2 weeks",
 allocation: "12%",
 catalyst: "Market rally",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "Moderate",
 diversification: "Balances sector risk",
 liquidity: "High",
 expected_return: "7%",
 performance: "Index up 13% YTD",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Trend Following"
 },
 {
 id: 44,
 name: "Ian",
 avatar: "https://randomuser.me/api/portraits/men/44.jpg",
 asset_type: "Indexes",
 sector: "Healthcare",
 tip: "Monitor BANKNIFTY as Healthcare improves.\nCentral bank decisions could matter.",
 symbol: "BANKNIFTY",
 created_at: "2025-06-12T05:00:00Z",
 entry_price: 42000,
 exit_price: 43000,
 target_duration: "3 weeks",
 allocation: "11%",
 catalyst: "Regulatory news",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "Moving average bullish crossover",
 confidence: "High",
 diversification: "Diversifies exposure",
 liquidity: "High",
 expected_return: "8%",
 performance: "Index up 12% YTD",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "88%",
 strategy: "Value Investing"
 },
 {
 id: 45,
 name: "Jane",
 avatar: "https://randomuser.me/api/portraits/women/45.jpg",
 asset_type: "Indexes",
 sector: "Healthcare",
 tip: "Follow SP500 to gauge market momentum.\nSector performances will play a role.",
 symbol: "SP500",
 created_at: "2025-06-11T06:00:00Z",
 entry_price: 3850,
 exit_price: 3700,
 target_duration: "1 week",
 allocation: "10%",
 catalyst: "Tech earnings",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "RSI at 52",
 confidence: "Moderate",
 diversification: "Balances sector risk",
 liquidity: "Very High",
 expected_return: "4%",
 performance: "Index up 10% YTD",
 holding: "Hold",
 risk: "Low",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Passive Indexing"
 },
 {
 id: 46,
 name: "Kyle",
 avatar: "https://randomuser.me/api/portraits/men/46.jpg",
 asset_type: "Indexes",
 sector: "Financials",
 tip: "Track NQ100 for broad market exposure.\nCentral bank actions matter.",
 symbol: "NQ100",
 created_at: "2025-06-10T07:00:00Z",
 entry_price: 19000,
 exit_price: 19500,
 target_duration: "2 weeks",
 allocation: "12%",
 catalyst: "Interest rate decision",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "Bollinger Bands widening",
 confidence: "High",
 diversification: "Complements portfolio",
 liquidity: "High",
 expected_return: "7%",
 performance: "Index up 16% YTD",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Trend Following"
 },
 {
 id: 47,
 name: "Lily",
 avatar: "https://randomuser.me/api/portraits/women/47.jpg",
 asset_type: "Indexes",
 sector: "Financials",
 tip: "Follow NIFTY50 to gauge market momentum.\nEarnings reports could shift it.",
 symbol: "NIFTY50",
 created_at: "2025-06-09T08:00:00Z",
 entry_price: 19500,
 exit_price: 19000,
 target_duration: "3 weeks",
 allocation: "9%",
 catalyst: "Earnings reports",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "RSI above 64",
 confidence: "Moderate",
 diversification: "Diversifies exposure",
 liquidity: "High",
 expected_return: "5%",
 performance: "Index up 14% YTD",
 holding: "Sell",
 risk: "High",
 conviction: "Medium",
 win_rate: "72%",
 strategy: "Speculative"
 },
 {
 id: 48,
 name: "Benjamin",
 avatar: "https://randomuser.me/api/portraits/men/48.jpg",
 asset_type: "Indexes",
 sector: "Technology",
 tip: "Follow IXIC to gauge market momentum.\nEconomic data or earnings may shift it.",
 symbol: "IXIC",
 created_at: "2025-06-08T09:00:00Z",
 entry_price: 237.73,
 exit_price: 259.20,
 target_duration: "2 days",
 allocation: "6%",
 catalyst: "Commodity price changes",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "Bollinger Bands widening",
 confidence: "Low",
 diversification: "Complements portfolio",
 liquidity: "High",
 expected_return: "3%",
 performance: "Index up 12% YTD",
 holding: "Buy",
 risk: "Low",
 conviction: "Weak",
 win_rate: "93%",
 strategy: "Trend Following"
 },

 // Asset Class: Bonds

 {
 id: 9,
 name: "Ivy",
 avatar: "https://randomuser.me/api/portraits/women/9.jpg",
 asset_type: "Bonds",
 sector: "Financials",
 tip: "Consider government bonds for stability.\nYields remain attractive in high-rate environment.",
 symbol: "GOVT",
 created_at: "2025-07-17T18:00:00Z",
 entry_price: 98,
 exit_price: 95,
 target_duration: "6 months",
 allocation: "20%",
 catalyst: "Federal Reserve policy",
 valuation: "Undervalued",
 sentiment: "Neutral",
 technical: "Yield curve steepening",
 confidence: "High",
 diversification: "Reduces portfolio volatility",
 liquidity: "Very High",
 expected_return: "3%",
 performance: "Last 3 tips: +2%, +1%, +3%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Income"
 },

 {
 id: 10,
 name: "Jack",
 avatar: "https://randomuser.me/api/portraits/men/10.jpg",
 asset_type: "Bonds",
 sector: "Technology",
 tip: "Tech bonds offer higher yields.\nSector growth supports bond performance.",
 symbol: "TECHBOND",
 created_at: "2025-07-16T19:00:00Z",
 entry_price: 105,
 exit_price: 102,
 target_duration: "3 months",
 allocation: "15%",
 catalyst: "Tech earnings growth",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "Stable yield trends",
 confidence: "Moderate",
 diversification: "Balances tech equity risk",
 liquidity: "Medium",
 expected_return: "4%",
 performance: "Last 3 tips: +3%, +2%, +4%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Income"
 },

 {
 id: 11,
 name: "Kate",
 avatar: "https://randomuser.me/api/portraits/women/11.jpg",
 asset_type: "Bonds",
 sector: "Energy",
 tip: "Energy bonds are less volatile.\nStable cash flows ensure bond reliability.",
 symbol: "ENBOND",
 created_at: "2025-07-15T20:00:00Z",
 entry_price: 100,
 exit_price: 98,
 target_duration: "1 year",
 allocation: "12%",
 catalyst: "Oil price stabilization",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Consistent yield support",
 confidence: "High",
 diversification: "Complements energy stocks",
 liquidity: "Medium",
 expected_return: "7%",
 performance: "Last 3 tips: +4%, +3%, +5%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },

 {
 id: 12,
 name: "Leo",
 avatar: "https://randomuser.me/api/portraits/men/12.jpg",
 asset_type: "Bonds",
 sector: "Healthcare",
 tip: "Healthcare bonds are a safe haven.\nStrong fundamentals reduce default risk.",
 symbol: "HCBOND",
 created_at: "2025-07-14T21:00:00Z",
 entry_price: 102,
 exit_price: 99,
 target_duration: "6 months",
 allocation: "10%",
 catalyst: "Healthcare reforms",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "Yield curve flattening",
 confidence: "High",
 diversification: "Reduces sector volatility",
 liquidity: "High",
 expected_return: "3%",
 performance: "Last 3 tips: +2%, +3%, +2%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "90%",
 strategy: "Income"
 },

 {
 id: 49,
 name: "Ivan",
 avatar: "https://randomuser.me/api/portraits/men/49.jpg",
 asset_type: "Bonds",
 sector: "Technology",
 tip: "Consider USTBOND for stability.\nYields remain attractive in current climate.",
 symbol: "USTBOND",
 created_at: "2025-06-17T10:00:00Z",
 entry_price: 102.50,
 exit_price: 100.80,
 target_duration: "1 year",
 allocation: "12%",
 catalyst: "Inflation data",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Yield curve steepening",
 confidence: "Moderate",
 diversification: "Reduces portfolio volatility",
 liquidity: "High",
 expected_return: "4%",
 performance: "Last 3 tips: +2%, +1%, +3%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Income"
 },
 {
 id: 50,
 name: "Jasmine",
 avatar: "https://randomuser.me/api/portraits/women/50.jpg",
 asset_type: "Bonds",
 sector: "Technology",
 tip: "Use USTBOND for stability.\nYields remain attractive in current climate.",
 symbol: "USTBOND",
 created_at: "2025-06-16T11:00:00Z",
 entry_price: 100.10,
 exit_price: 98.90,
 target_duration: "2 months",
 allocation: "10%",
 catalyst: "Federal Reserve policy",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Stable yield trends",
 confidence: "High",
 diversification: "Reduces portfolio volatility",
 liquidity: "High",
 expected_return: "3%",
 performance: "Last 3 tips: +2%, +0%, +1%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Income"
 },
 {
 id: 51,
 name: "Kevin",
 avatar: "https://randomuser.me/api/portraits/men/51.jpg",
 asset_type: "Bonds",
 sector: "Energy",
 tip: "Consider OILBOND for income.\nStable cash flows support yields.",
 symbol: "OILBOND",
 created_at: "2025-06-15T12:00:00Z",
 entry_price: 108.20,
 exit_price: 106.50,
 target_duration: "6 months",
 allocation: "8%",
 catalyst: "Oil production news",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Consistent yield support",
 confidence: "Moderate",
 diversification: "Complements energy stocks",
 liquidity: "Medium",
 expected_return: "5%",
 performance: "Last 3 tips: +3%, +2%, +4%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Income"
 },
 {
 id: 52,
 name: "Laura",
 avatar: "https://randomuser.me/api/portraits/women/52.jpg",
 asset_type: "Bonds",
 sector: "Energy",
 tip: "Energy bonds offer stability.\nStable cash flows support yields.",
 symbol: "OILBOND",
 created_at: "2025-06-14T13:00:00Z",
 entry_price: 107.45,
 exit_price: 105.80,
 target_duration: "3 months",
 allocation: "9%",
 catalyst: "Oil price movement",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Yield curve flattening",
 confidence: "Moderate",
 diversification: "Complements energy stocks",
 liquidity: "Medium",
 expected_return: "4%",
 performance: "Last 3 tips: +2%, +1%, +3%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },
 {
 id: 53,
 name: "Michael",
 avatar: "https://randomuser.me/api/portraits/men/53.jpg",
 asset_type: "Bonds",
 sector: "Healthcare",
 tip: "Consider CORPBOND for higher income.\nCompanies are generating steady cash flow.",
 symbol: "CORPBOND",
 created_at: "2025-06-13T14:00:00Z",
 entry_price: 111.20,
 exit_price: 109.60,
 target_duration: "1 year",
 allocation: "10%",
 catalyst: "Corporate earnings",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "Stable yield trends",
 confidence: "High",
 diversification: "Balances portfolio risk",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +4%, +3%, +5%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Income"
 },
 {
 id: 54,
 name: "Natalie",
 avatar: "https://randomuser.me/api/portraits/women/54.jpg",
 asset_type: "Bonds",
 sector: "Healthcare",
 tip: "FINBOND has solid returns.\nStable cash flows support yields.",
 symbol: "FINBOND",
 created_at: "2025-06-12T15:00:00Z",
 entry_price: 110.00,
 exit_price: 108.50,
 target_duration: "6 months",
 allocation: "11%",
 catalyst: "Regulatory changes",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Consistent yield support",
 confidence: "High",
 diversification: "Balances portfolio risk",
 liquidity: "Medium",
 expected_return: "5%",
 performance: "Last 3 tips: +3%, +2%, +4%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "82%",
 strategy: "Income"
 },
 {
 id: 55,
 name: "Oliver",
 avatar: "https://randomuser.me/api/portraits/men/55.jpg",
 asset_type: "Bonds",
 sector: "Financials",
 tip: "BND offers broad exposure.\nGovernment bonds are stable.",
 symbol: "BND",
 created_at: "2025-06-11T16:00:00Z",
 entry_price: 98.50,
 exit_price: 97.80,
 target_duration: "6 months",
 allocation: "12%",
 catalyst: "Fed meeting",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "Yield curve steepening",
 confidence: "High",
 diversification: "Core portfolio holding",
 liquidity: "High",
 expected_return: "3%",
 performance: "Last 3 tips: +2%, +1%, +2%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Income"
 },
 {
 id: 56,
 name: "Paul",
 avatar: "https://randomuser.me/api/portraits/men/56.jpg",
 asset_type: "Bonds",
 sector: "Financials",
 tip: "USTBOND for government exposure.\nSafe yield in uncertain times.",
 symbol: "USTBOND",
 created_at: "2025-06-10T17:00:00Z",
 entry_price: 99.10,
 exit_price: 98.40,
 target_duration: "1 year",
 allocation: "15%",
 catalyst: "Economic reports",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Stable yield trends",
 confidence: "High",
 diversification: "Core portfolio holding",
 liquidity: "Very High",
 expected_return: "3%",
 performance: "Last 3 tips: +1%, +0%, +1%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "87%",
 strategy: "Income"
 },

 // Asset Class: Commodities

 {
 id: 13,
 name: "Mona",
 avatar: "https://randomuser.me/api/portraits/women/13.jpg",
 asset_type: "Commodities",
 sector: "Energy",
 tip: "Gold is a hedge against inflation.\nRising rates increase its appeal.",
 symbol: "GOLD",
 created_at: "2025-07-13T22:00:00Z",
 entry_price: 1800,
 exit_price: 1750,
 target_duration: "1 month",
 allocation: "8%",
 catalyst: "Inflation data release",
 valuation: "Overvalued",
 sentiment: "Neutral",
 technical: "RSI at 50, neutral trend",
 confidence: "Moderate",
 diversification: "Balances equity risk",
 liquidity: "High",
 expected_return: "5%",
 performance: "Last 3 tips: +6%, +4%, +7%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Safe Haven"
 },

 {
 id: 14,
 name: "Nate",
 avatar: "https://randomuser.me/api/portraits/men/14.jpg",
 asset_type: "Commodities",
 sector: "Financials",
 tip: "Silver demand rises in electronics.\nIndustrial use drives price growth.",
 symbol: "SILVER",
 created_at: "2025-07-12T23:00:00Z",
 entry_price: 25,
 exit_price: 23,
 target_duration: "2 weeks",
 allocation: "7%",
 catalyst: "Tech production increase",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "MACD bullish signal",
 confidence: "Moderate",
 diversification: "Complements tech assets",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +5%, +3%, +6%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Momentum"
 },

 {
 id: 15,
 name: "Olivia",
 avatar: "https://randomuser.me/api/portraits/women/15.jpg",
 asset_type: "Commodities",
 sector: "Technology",
 tip: "Copper prices may rise with tech.\nData center expansion drives demand.",
 symbol: "COPPER",
 created_at: "2025-07-11T00:00:00Z",
 entry_price: 4.5,
 exit_price: 4.2,
 target_duration: "1 month",
 allocation: "6%",
 catalyst: "Tech infrastructure growth",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "RSI below 40, oversold",
 confidence: "High",
 diversification: "Enhances tech exposure",
 liquidity: "Medium",
 expected_return: "8%",
 performance: "Last 3 tips: +7%, +5%, +8%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Growth"
 },

 {
 id: 16,
 name: "Paul",
 avatar: "https://randomuser.me/api/portraits/men/16.jpg",
 asset_type: "Commodities",
 sector: "Healthcare",
 tip: "Platinum used in medical devices.\nHealthcare innovation boosts demand.",
 symbol: "PLATINUM",
 created_at: "2025-07-10T01:00:00Z",
 entry_price: 1000,
 exit_price: 950,
 target_duration: "3 weeks",
 allocation: "5%",
 catalyst: "Medical tech advancements",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "50DMA support",
 confidence: "Moderate",
 diversification: "Balances healthcare portfolio",
 liquidity: "Medium",
 expected_return: "6%",
 performance: "Last 3 tips: +4%, +5%, +3%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Value"
 },
 {
 id: 58,
 name: "Quentin",
 avatar: "https://randomuser.me/api/portraits/men/58.jpg",
 asset_type: "Commodities",
 sector: "Technology",
 tip: "Coffee demand is rising in emerging markets.\nSupply chain issues may impact prices.",
 symbol: "COFFEE",
 created_at: "2025-06-09T10:00:00Z",
 entry_price: 130.45,
 exit_price: 125.30,
 target_duration: "1 month",
 allocation: "7%",
 catalyst: "Supply disruptions",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "RSI at 55",
 confidence: "Moderate",
 diversification: "Diversifies portfolio",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +3%, +2%, +1%",
 holding: "Hold",
 risk: "High",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Growth"
 },
 {
 id: 59,
 name: "Rebecca",
 avatar: "https://randomuser.me/api/portraits/women/59.jpg",
 asset_type: "Commodities",
 sector: "Technology",
 tip: "Monitor SILVER amid tech demand.\nIndustrial consumption may keep prices high.",
 symbol: "SILVER",
 created_at: "2025-06-08T11:00:00Z",
 entry_price: 28.90,
 exit_price: 27.15,
 target_duration: "2 weeks",
 allocation: "5%",
 catalyst: "Industrial demand",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "RSI above 60",
 confidence: "Moderate",
 diversification: "Balances tech exposure",
 liquidity: "High",
 expected_return: "4%",
 performance: "Last 3 tips: +2%, +1%, -1%",
 holding: "Sell",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "65%",
 strategy: "Momentum"
 },
 {
 id: 60,
 name: "Sean",
 avatar: "https://randomuser.me/api/portraits/men/60.jpg",
 asset_type: "Commodities",
 sector: "Energy",
 tip: "Copper shows bullish trend.\nImproving global demand drives prices.",
 symbol: "COPPER",
 created_at: "2025-06-07T12:00:00Z",
 entry_price: 4.8,
 exit_price: 5.1,
 target_duration: "2 weeks",
 allocation: "6%",
 catalyst: "Industrial demand",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "RSI above 55",
 confidence: "High",
 diversification: "Balances tech exposure",
 liquidity: "High",
 expected_return: "8%",
 performance: "Last 3 tips: +7%, +6%, +8%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Momentum"
 },
 {
 id: 61,
 name: "Tracy",
 avatar: "https://randomuser.me/api/portraits/women/61.jpg",
 asset_type: "Commodities",
 sector: "Energy",
 tip: "Sugar prices may rise.\nDemand from food sector increases.",
 symbol: "SUGAR",
 created_at: "2025-06-06T13:00:00Z",
 entry_price: 15.20,
 exit_price: 16.45,
 target_duration: "1 month",
 allocation: "8%",
 catalyst: "Food demand",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "MACD bullish signal",
 confidence: "Moderate",
 diversification: "Diversifies portfolio",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +6%, +4%, +5%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Trend Following"
 },
 {
 id: 62,
 name: "Uma",
 avatar: "https://randomuser.me/api/portraits/women/62.jpg",
 asset_type: "Commodities",
 sector: "Healthcare",
 tip: "Gold remains steady.\nSafe-haven appeal in volatile markets.",
 symbol: "GOLD",
 created_at: "2025-06-05T14:00:00Z",
 entry_price: 1805.10,
 exit_price: 1790.40,
 target_duration: "1 month",
 allocation: "7%",
 catalyst: "Inflation data",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Bollinger Bands narrowing",
 confidence: "Moderate",
 diversification: "Safe-haven asset",
 liquidity: "High",
 expected_return: "5%",
 performance: "Last 3 tips: +2%, +1%, +3%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "78%",
 strategy: "Safe Haven"
 },
 {
 id: 63,
 name: "Victor",
 avatar: "https://randomuser.me/api/portraits/men/63.jpg",
 asset_type: "Commodities",
 sector: "Healthcare",
 tip: "Platinum demand holds steady.\nIndustrial use maintains support.",
 symbol: "PLATINUM",
 created_at: "2025-06-04T15:00:00Z",
 entry_price: 1020.00,
 exit_price: 1010.00,
 target_duration: "2 weeks",
 allocation: "5%",
 catalyst: "Industrial demand",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "50DMA support",
 confidence: "Moderate",
 diversification: "Diversifies portfolio",
 liquidity: "High",
 expected_return: "4%",
 performance: "Last 3 tips: +3%, +2%, +4%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "72%",
 strategy: "Value"
 },
 {
 id: 64,
 name: "Wendy",
 avatar: "https://randomuser.me/api/portraits/women/64.jpg",
 asset_type: "Commodities",
 sector: "Financials",
 tip: "Wheat prices stabilize.\nGlobal supply supports current prices.",
 symbol: "WHEAT",
 created_at: "2025-06-03T16:00:00Z",
 entry_price: 700,
 exit_price: 680,
 target_duration: "3 months",
 allocation: "6%",
 catalyst: "Weather reports",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Moving average resistance",
 confidence: "High",
 diversification: "Diversifies portfolio",
 liquidity: "High",
 expected_return: "5%",
 performance: "Last 3 tips: +4%, +3%, +5%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },
 {
 id: 65,
 name: "Xander",
 avatar: "https://randomuser.me/api/portraits/men/65.jpg",
 asset_type: "Commodities",
 sector: "Financials",
 tip: "Natural gas remains in demand.\nCold weather drives prices up.",
 symbol: "NGAS",
 created_at: "2025-06-02T17:00:00Z",
 entry_price: 4.00,
 exit_price: 4.20,
 target_duration: "1 month",
 allocation: "7%",
 catalyst: "Weather forecasts",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "RSI above 60",
 confidence: "High",
 diversification: "Diversifies energy exposure",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +5%, +4%, +6%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Growth"
 },

 // Asset Class: Forex

 {
 id: 17,
 name: "Quinn",
 avatar: "https://randomuser.me/api/portraits/women/17.jpg",
 asset_type: "Forex",
 sector: "Financials",
 tip: "USD/INR expected to remain stable.\nRBI policies support currency balance.",
 symbol: "USDINR",
 created_at: "2025-07-09T02:00:00Z",
 entry_price: 83.5,
 exit_price: 82.5,
 target_duration: "2 weeks",
 allocation: "10%",
 catalyst: "RBI monetary policy",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Bollinger Bands narrowing",
 confidence: "High",
 diversification: "Reduces currency risk",
 liquidity: "Very High",
 expected_return: "3%",
 performance: "Last 3 tips: +2%, +1%, +3%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Stability"
 },

 {
 id: 18,
 name: "Ray",
 avatar: "https://randomuser.me/api/portraits/men/18.jpg",
 asset_type: "Forex",
 sector: "Technology",
 tip: "EUR/USD may see volatility soon.\nTech earnings could impact pair.",
 symbol: "EURUSD",
 created_at: "2025-07-08T03:00:00Z",
 entry_price: 1.09,
 exit_price: 1.07,
 target_duration: "1 week",
 allocation: "8%",
 catalyst: "Tech earnings reports",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "RSI above 65",
 confidence: "Moderate",
 diversification: "Balances tech exposure",
 liquidity: "Very High",
 expected_return: "4%",
 performance: "Last 3 tips: +3%, -1%, +4%",
 holding: "Sell",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Speculative"
 },

 {
 id: 19,
 name: "Sara",
 avatar: "https://randomuser.me/api/portraits/women/19.jpg",
 asset_type: "Forex",
 sector: "Energy",
 tip: "AUD/USD correlates with oil prices.\nEnergy market trends drive pair.",
 symbol: "AUDUSD",
 created_at: "2025-07-07T04:00:00Z",
 entry_price: 0.67,
 exit_price: 0.65,
 target_duration: "2 weeks",
 allocation: "7%",
 catalyst: "Oil price fluctuations",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "MACD bullish signal",
 confidence: "Moderate",
 diversification: "Complements energy assets",
 liquidity: "High",
 expected_return: "5%",
 performance: "Last 3 tips: +4%, +2%, +5%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Trend Following"
 },

 {
 id: 20,
 name: "Tom",
 avatar: "https://randomuser.me/api/portraits/men/20.jpg",
 asset_type: "Forex",
 sector: "Healthcare",
 tip: "JPY may strengthen on reforms.\nHealthcare policies boost currency.",
 symbol: "USDJPY",
 created_at: "2025-07-06T05:00:00Z",
 entry_price: 155,
 exit_price: 150,
 target_duration: "1 month",
 allocation: "6%",
 catalyst: "Healthcare reforms",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "RSI below 40, oversold",
 confidence: "High",
 diversification: "Reduces forex volatility",
 liquidity: "Very High",
 expected_return: "6%",
 performance: "Last 3 tips: +5%, +3%, +6%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Value"
 },
 {
 id: 66,
 name: "Uma",
 avatar: "https://randomuser.me/api/portraits/women/66.jpg",
 asset_type: "Forex",
 sector: "Technology",
 tip: "USD/CAD is steady.\nStable trends expected ahead.",
 symbol: "USDCAD",
 created_at: "2025-06-06T18:00:00Z",
 entry_price: 1.34,
 exit_price: 1.33,
 target_duration: "2 weeks",
 allocation: "10%",
 catalyst: "Fed meeting",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "MACD neutral",
 confidence: "Moderate",
 diversification: "Reduces currency risk",
 liquidity: "Very High",
 expected_return: "2%",
 performance: "Last 3 tips: +1%, +0%, +1%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Stability"
 },
 {
 id: 67,
 name: "Victor",
 avatar: "https://randomuser.me/api/portraits/men/67.jpg",
 asset_type: "Forex",
 sector: "Energy",
 tip: "Monitor NZD/USD with commodity trends.\nRecent demand influences rate.",
 symbol: "NZDUSD",
 created_at: "2025-06-05T19:00:00Z",
 entry_price: 0.66,
 exit_price: 0.68,
 target_duration: "3 weeks",
 allocation: "8%",
 catalyst: "Commodity data",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "High",
 diversification: "Reduces forex volatility",
 liquidity: "Very High",
 expected_return: "5%",
 performance: "Last 3 tips: +4%, +3%, +6%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Trend Following"
 },
 {
 id: 68,
 name: "Wendy",
 avatar: "https://randomuser.me/api/portraits/women/68.jpg",
 asset_type: "Forex",
 sector: "Healthcare",
 tip: "GBP/USD influenced by policy.\nCentral bank decisions matter.",
 symbol: "GBPUSD",
 created_at: "2025-06-04T20:00:00Z",
 entry_price: 1.22,
 exit_price: 1.20,
 target_duration: "2 weeks",
 allocation: "7%",
 catalyst: "Interest rate",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "RSI above 70",
 confidence: "Moderate",
 diversification: "Balances currency risk",
 liquidity: "Very High",
 expected_return: "4%",
 performance: "Last 3 tips: +3%, +1%, +2%",
 holding: "Sell",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Speculative"
 },
 {
 id: 69,
 name: "Xander",
 avatar: "https://randomuser.me/api/portraits/men/69.jpg",
 asset_type: "Forex",
 sector: "Financials",
 tip: "USD/CNY reflects trade tensions.\nGlobal news drives movement.",
 symbol: "USDCNY",
 created_at: "2025-06-03T21:00:00Z",
 entry_price: 7.15,
 exit_price: 7.10,
 target_duration: "1 month",
 allocation: "9%",
 catalyst: "Trade news",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "MACD neutral",
 confidence: "Moderate",
 diversification: "Balances currency risk",
 liquidity: "Very High",
 expected_return: "3%",
 performance: "Last 3 tips: +2%, +0%, +1%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "82%",
 strategy: "Stability"
 },
 {
 id: 70,
 name: "Yara",
 avatar: "https://randomuser.me/api/portraits/women/70.jpg",
 asset_type: "Forex",
 sector: "Financials",
 tip: "EUR/CHF remains calm.\nSwitzerland's monetary policy at play.",
 symbol: "USDCHF",
 created_at: "2025-06-02T22:00:00Z",
 entry_price: 0.92,
 exit_price: 0.91,
 target_duration: "1 week",
 allocation: "6%",
 catalyst: "Central bank meeting",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "RSI at 49",
 confidence: "High",
 diversification: "Balances currency risk",
 liquidity: "Very High",
 expected_return: "3%",
 performance: "Last 3 tips: +2%, +1%, +1%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "84%",
 strategy: "Stability"
 },

 // Asset Class: Equity

 {
 id: 21,
 name: "Uma",
 avatar: "https://randomuser.me/api/portraits/women/21.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Apple stock remains a strong buy.\nInnovation drives long-term growth.",
 symbol: "AAPL",
 created_at: "2025-07-05T06:00:00Z",
 entry_price: 180,
 exit_price: 170,
 target_duration: "3 months",
 allocation: "15%",
 catalyst: "Product launch",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "RSI at 55, uptrend",
 confidence: "High",
 diversification: "Core tech holding",
 liquidity: "Very High",
 expected_return: "10%",
 performance: "Last 3 tips: +8%, +6%, +9%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Growth"
 },

 {
 id: 22,
 name: "Victor",
 avatar: "https://randomuser.me/api/portraits/men/22.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "Bank of America shows potential.\nStrong Q2 earnings support growth.",
 symbol: "BAC",
 created_at: "2025-07-04T07:00:00Z",
 entry_price: 40,
 exit_price: 38,
 target_duration: "2 months",
 allocation: "12%",
 catalyst: "Earnings report",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "Moderate",
 diversification: "Balances financial exposure",
 liquidity: "High",
 expected_return: "8%",
 performance: "Last 3 tips: +6%, +4%, +7%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Value"
 },

 {
 id: 23,
 name: "Wendy",
 avatar: "https://randomuser.me/api/portraits/women/23.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "ExxonMobil is a solid dividend stock.\nEnergy demand supports stability.",
 symbol: "XOM",
 created_at: "2025-07-03T08:00:00Z",
 entry_price: 110,
 exit_price: 105,
 target_duration: "6 months",
 allocation: "10%",
 catalyst: "Oil price recovery",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "50DMA support",
 confidence: "High",
 diversification: "Reduces sector risk",
 liquidity: "High",
 expected_return: "7%",
 performance: "Last 3 tips: +5%, +3%, +6%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },

 {
 id: 24,
 name: "Xander",
 avatar: "https://randomuser.me/api/portraits/men/24.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Pfizer has strong R&D pipeline.\nNew drugs drive stock growth.",
 symbol: "PFE",
 created_at: "2025-07-02T09:00:00Z",
 entry_price: 50,
 exit_price: 48,
 target_duration: "3 months",
 allocation: "8%",
 catalyst: "Drug approvals",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "RSI below 45, oversold",
 confidence: "High",
 diversification: "Complements healthcare portfolio",
 liquidity: "High",
 expected_return: "9%",
 performance: "Last 3 tips: +7%, +5%, +8%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Growth"
 },
 {
 id: 74,
 name: "Michael",
 avatar: "https://randomuser.me/api/portraits/men/74.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "WFC bank remains solid.\nMarket expects steady growth.",
 symbol: "WFC",
 created_at: "2025-05-07T10:00:00Z",
 entry_price: 48,
 exit_price: 50,
 target_duration: "1 month",
 allocation: "6%",
 catalyst: "Stable economy",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "Moderate",
 diversification: "Core financial holding",
 liquidity: "High",
 expected_return: "7%",
 performance: "Last 3 tips: +4%, +5%, +6%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Value"
 },
 {
 id: 75,
 name: "Nina",
 avatar: "https://randomuser.me/api/portraits/women/75.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "JPM shows steady growth.\nStrong fundamentals support gains.",
 symbol: "JPM",
 created_at: "2025-05-08T11:00:00Z",
 entry_price: 155,
 exit_price: 150,
 target_duration: "1 month",
 allocation: "7%",
 catalyst: "Financial reports",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "RSI at 50",
 confidence: "Moderate",
 diversification: "Balances financial exposure",
 liquidity: "High",
 expected_return: "5%",
 performance: "Last 3 tips: +3%, +2%, +1%",
 holding: "Hold",
 risk: "Low",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Value"
 },
 {
 id: 76,
 name: "Oliver",
 avatar: "https://randomuser.me/api/portraits/men/76.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "Intel remains a core tech pick.\nChip demand supports growth.",
 symbol: "INTC",
 created_at: "2025-05-09T12:00:00Z",
 entry_price: 52,
 exit_price: 55,
 target_duration: "2 months",
 allocation: "5%",
 catalyst: "Tech sector demand",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "High",
 diversification: "Enhances tech portfolio",
 liquidity: "High",
 expected_return: "8%",
 performance: "Last 3 tips: +7%, +6%, +8%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Growth"
 },
 {
 id: 77,
 name: "Pamela",
 avatar: "https://randomuser.me/api/portraits/women/77.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "Merck stock is stable.\nDefensive play amid volatility.",
 symbol: "MRK",
 created_at: "2025-05-10T13:00:00Z",
 entry_price: 82,
 exit_price: 80,
 target_duration: "1 month",
 allocation: "6%",
 catalyst: "Health sector news",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "50DMA support",
 confidence: "Moderate",
 diversification: "Defensive sector exposure",
 liquidity: "High",
 expected_return: "5%",
 performance: "Last 3 tips: +4%, +3%, +2%",
 holding: "Hold",
 risk: "Low",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Income"
 },
 {
 id: 78,
 name: "Quinn",
 avatar: "https://randomuser.me/api/portraits/women/78.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Oracle stock has upside potential.\nStrong demand in cloud segment.",
 symbol: "ORCL",
 created_at: "2025-05-11T14:00:00Z",
 entry_price: 78,
 exit_price: 81,
 target_duration: "2 months",
 allocation: "7%",
 catalyst: "Cloud services demand",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "High",
 diversification: "Balances tech exposure",
 liquidity: "High",
 expected_return: "10%",
 performance: "Last 3 tips: +8%, +7%, +6%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Growth"
 },
 {
 id: 79,
 name: "Rebecca",
 avatar: "https://randomuser.me/api/portraits/women/79.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Johnson & Johnson is stable.\nHealthcare demand drives returns.",
 symbol: "JNJ",
 created_at: "2025-05-12T15:00:00Z",
 entry_price: 155,
 exit_price: 152,
 target_duration: "3 months",
 allocation: "8%",
 catalyst: "Healthcare news",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "50DMA support",
 confidence: "High",
 diversification: "Defensive stock",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +5%, +4%, +6%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },

 // Asset Class: Mutual Funds

 {
 id: 25,
 name: "Yara",
 avatar: "https://randomuser.me/api/portraits/women/25.jpg",
 asset_type: "Mutual Funds",
 sector: "Financials",
 tip: "SBI Bluechip Fund is a long-term pick.\nFinancials show consistent growth.",
 symbol: "SBIBLUECHIP",
 created_at: "2025-07-01T10:00:00Z",
 entry_price: 70,
 exit_price: 65,
 target_duration: "1 year",
 allocation: "15%",
 catalyst: "Financial sector recovery",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "NAV uptrend",
 confidence: "High",
 diversification: "Core portfolio holding",
 liquidity: "Medium",
 expected_return: "10%",
 performance: "Last 3 tips: +8%, +6%, +9%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Long-Term Growth"
 },

 {
 id: 26,
 name: "Zane",
 avatar: "https://randomuser.me/api/portraits/men/26.jpg",
 asset_type: "Mutual Funds",
 sector: "Technology",
 tip: "Tech mutual funds outperform in 2024.\nInnovation drives fund performance.",
 symbol: "TECHFUND",
 created_at: "2025-06-30T11:00:00Z",
 entry_price: 120,
 exit_price: 110,
 target_duration: "6 months",
 allocation: "12%",
 catalyst: "Tech sector growth",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "RSI above 60",
 confidence: "Moderate",
 diversification: "Balances tech exposure",
 liquidity: "Medium",
 expected_return: "8%",
 performance: "Last 3 tips: +7%, +5%, +8%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Growth"
 },

 {
 id: 27,
 name: "Ava",
 avatar: "https://randomuser.me/api/portraits/women/27.jpg",
 asset_type: "Mutual Funds",
 sector: "Energy",
 tip: "Energy funds are defensive in downturns.\nStable cash flows ensure returns.",
 symbol: "ENFUND",
 created_at: "2025-06-29T12:00:00Z",
 entry_price: 90,
 exit_price: 85,
 target_duration: "1 year",
 allocation: "10%",
 catalyst: "Oil price stability",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "NAV stable",
 confidence: "High",
 diversification: "Reduces energy risk",
 liquidity: "Medium",
 expected_return: "6%",
 performance: "Last 3 tips: +5%, +4%, +6%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },

 {
 id: 28,
 name: "Ben",
 avatar: "https://randomuser.me/api/portraits/men/28.jpg",
 asset_type: "Mutual Funds",
 sector: "Healthcare",
 tip: "Healthcare funds offer stability.\nStrong R&D supports growth.",
 symbol: "HCFUND",
 created_at: "2025-06-28T13:00:00Z",
 entry_price: 100,
 exit_price: 95,
 target_duration: "1 year",
 allocation: "8%",
 catalyst: "Healthcare innovations",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "NAV uptrend",
 confidence: "High",
 diversification: "Balances healthcare portfolio",
 liquidity: "Medium",
 expected_return: "7%",
 performance: "Last 3 tips: +6%, +5%, +7%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Long-Term Growth"
 },
 {
 id: 82,
 name: "Zoey",
 avatar: "https://randomuser.me/api/portraits/women/82.jpg",
 asset_type: "Mutual Funds",
 sector: "Technology",
 tip: "IT fund outperforms tech stocks.\nLong-term innovation drives NAV up.",
 symbol: "ITFUND",
 created_at: "2025-06-27T14:00:00Z",
 entry_price: 120,
 exit_price: 115,
 target_duration: "6 months",
 allocation: "12%",
 catalyst: "Tech growth",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "NAV uptrend",
 confidence: "Moderate",
 diversification: "Balances tech exposure",
 liquidity: "Medium",
 expected_return: "8%",
 performance: "Last 3 tips: +6%, +5%, +7%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Growth"
 },
 {
 id: 83,
 name: "Andrew",
 avatar: "https://randomuser.me/api/portraits/men/83.jpg",
 asset_type: "Mutual Funds",
 sector: "Technology",
 tip: "Tech growth fund remains strong.\nInnovation fuels performance.",
 symbol: "DIGIFUND",
 created_at: "2025-06-26T15:00:00Z",
 entry_price: 90,
 exit_price: 88,
 target_duration: "6 months",
 allocation: "10%",
 catalyst: "Tech sector growth",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "NAV uptrend",
 confidence: "High",
 diversification: "Balances tech exposure",
 liquidity: "Medium",
 expected_return: "9%",
 performance: "Last 3 tips: +7%, +6%, +8%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Long-Term Growth"
 },
 {
 id: 84,
 name: "Beth",
 avatar: "https://randomuser.me/api/portraits/women/84.jpg",
 asset_type: "Mutual Funds",
 sector: "Energy",
 tip: "Oil fund offers good yields.\nStable returns in volatile markets.",
 symbol: "OILFUND",
 created_at: "2025-06-25T16:00:00Z",
 entry_price: 50,
 exit_price: 48,
 target_duration: "1 year",
 allocation: "9%",
 catalyst: "Oil price stabilization",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "NAV stable",
 confidence: "High",
 diversification: "Reduces energy risk",
 liquidity: "Medium",
 expected_return: "6%",
 performance: "Last 3 tips: +4%, +3%, +5%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },
 {
 id: 85,
 name: "Carl",
 avatar: "https://randomuser.me/api/portraits/men/85.jpg",
 asset_type: "Mutual Funds",
 sector: "Energy",
 tip: "Green fund is steady.\nDiversifies energy exposure.",
 symbol: "GREENFUND",
 created_at: "2025-06-24T17:00:00Z",
 entry_price: 45,
 exit_price: 43,
 target_duration: "1 year",
 allocation: "8%",
 catalyst: "Energy demand",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "NAV uptrend",
 confidence: "Moderate",
 diversification: "Balances energy exposure",
 liquidity: "Medium",
 expected_return: "5%",
 performance: "Last 3 tips: +3%, +2%, +4%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },
 {
 id: 86,
 name: "Diana",
 avatar: "https://randomuser.me/api/portraits/women/86.jpg",
 asset_type: "Mutual Funds",
 sector: "Healthcare",
 tip: "BondPLUS is safe.\nGovernment securities fund for stability.",
 symbol: "BONDPLUS",
 created_at: "2025-06-23T18:00:00Z",
 entry_price: 100,
 exit_price: 100,
 target_duration: "1 year",
 allocation: "10%",
 catalyst: "Stable policy rates",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "NAV stable",
 confidence: "High",
 diversification: "Reduces volatility",
 liquidity: "Medium",
 expected_return: "3%",
 performance: "Last 3 tips: +1%, +1%, +1%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "90%",
 strategy: "Income"
 },
 {
 id: 87,
 name: "Ethan",
 avatar: "https://randomuser.me/api/portraits/men/87.jpg",
 asset_type: "Mutual Funds",
 sector: "Financials",
 tip: "FINFUND delivers stable returns.\nConsistent performance in finance sector.",
 symbol: "FINFUND",
 created_at: "2025-06-22T19:00:00Z",
 entry_price: 65,
 exit_price: 62,
 target_duration: "1 year",
 allocation: "8%",
 catalyst: "Bank earnings",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "NAV uptrend",
 confidence: "High",
 diversification: "Balances financial exposure",
 liquidity: "Medium",
 expected_return: "7%",
 performance: "Last 3 tips: +5%, +4%, +6%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Growth"
 },
 {
 id: 88,
 name: "Fiona",
 avatar: "https://randomuser.me/api/portraits/women/88.jpg",
 asset_type: "Mutual Funds",
 sector: "Healthcare",
 tip: "MEDFUND is a defensive pick.\nStable returns from pharma sector.",
 symbol: "MEDFUND",
 created_at: "2025-06-21T20:00:00Z",
 entry_price: 98,
 exit_price: 94,
 target_duration: "6 months",
 allocation: "10%",
 catalyst: "Healthcare pipeline",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "NAV stable",
 confidence: "Moderate",
 diversification: "Balances healthcare exposure",
 liquidity: "Medium",
 expected_return: "6%",
 performance: "Last 3 tips: +4%, +3%, +5%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },
 {
 id: 89,
 name: "Grace",
 avatar: "https://randomuser.me/api/portraits/women/89.jpg",
 asset_type: "Mutual Funds",
 sector: "Technology",
 tip: "TECHFUND2 captures tech growth.\nInnovation drives NAV upward.",
 symbol: "TECHFUND2",
 created_at: "2025-06-20T21:00:00Z",
 entry_price: 75,
 exit_price: 72,
 target_duration: "6 months",
 allocation: "9%",
 catalyst: "Tech earnings",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "NAV uptrend",
 confidence: "High",
 diversification: "Balances tech exposure",
 liquidity: "Medium",
 expected_return: "7%",
 performance: "Last 3 tips: +6%, +5%, +7%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Growth"
 },

 // Asset Class: Crypto

 {
 id: 29,
 name: "Cara",
 avatar: "https://randomuser.me/api/portraits/women/29.jpg",
 asset_type: "Crypto",
 sector: "Technology",
 tip: "Bitcoin remains the top crypto asset.\nAdoption drives long-term value.",
 symbol: "BTCUSD",
 created_at: "2025-06-27T14:00:00Z",
 entry_price: 60000,
 exit_price: 55000,
 target_duration: "1 month",
 allocation: "5%",
 catalyst: "Institutional adoption",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "RSI above 65",
 confidence: "Moderate",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "15%",
 performance: "Last 3 tips: +10%, +8%, +12%",
 holding: "Buy",
 risk: "High",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Speculative"
 },
 {
 id: 90,
 name: "Cara",
 avatar: "https://randomuser.me/api/portraits/women/90.jpg",
 asset_type: "Crypto",
 sector: "Technology",
 tip: "Ethereum’s smart contracts drive long-term value.\nAdoption trends boost outlook.",
 symbol: "ETHUSD",
 created_at: "2025-06-07T00:00:00Z",
 entry_price: 4200,
 exit_price: 4000,
 target_duration: "2 weeks",
 allocation: "4%",
 catalyst: "DeFi growth",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "High",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "12%",
 performance: "Last 3 tips: +10%, +8%, +9%",
 holding: "Buy",
 risk: "High",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Speculative"
 },
 {
 id: 91,
 name: "Danny",
 avatar: "https://randomuser.me/api/portraits/men/91.jpg",
 asset_type: "Crypto",
 sector: "Technology",
 tip: "Litecoin offers diversification.\nVolatility remains high but potential persists.",
 symbol: "LTCUSD",
 created_at: "2025-06-06T01:00:00Z",
 entry_price: 180,
 exit_price: 170,
 target_duration: "1 week",
 allocation: "3%",
 catalyst: "Market sentiment",
 valuation: "Overvalued",
 sentiment: "Neutral",
 technical: "RSI at 50",
 confidence: "Moderate",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "10%",
 performance: "Last 3 tips: +8%, +6%, +7%",
 holding: "Hold",
 risk: "High",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Speculative"
 },
 {
 id: 92,
 name: "Elena",
 avatar: "https://randomuser.me/api/portraits/women/92.jpg",
 asset_type: "Crypto",
 sector: "Technology",
 tip: "XRP sees network growth.\nBanking adoption may drive movement.",
 symbol: "XRPUSD",
 created_at: "2025-06-05T02:00:00Z",
 entry_price: 1.10,
 exit_price: 1.15,
 target_duration: "2 weeks",
 allocation: "3%",
 catalyst: "Banking adoption",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "MACD bullish signal",
 confidence: "High",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "15%",
 performance: "Last 3 tips: +12%, +10%, +8%",
 holding: "Buy",
 risk: "High",
 conviction: "Strong",
 win_rate: "78%",
 strategy: "Growth"
 },
 {
 id: 93,
 name: "Frankie",
 avatar: "https://randomuser.me/api/portraits/men/93.jpg",
 asset_type: "Crypto",
 sector: "Technology",
 tip: "Dogecoin remains speculative.\nCommunity sentiment drives its price.",
 symbol: "DOGEUSD",
 created_at: "2025-06-04T03:00:00Z",
 entry_price: 0.50,
 exit_price: 0.55,
 target_duration: "1 month",
 allocation: "2%",
 catalyst: "Social media buzz",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "RSI below 40, oversold",
 confidence: "Moderate",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "15%",
 performance: "Last 3 tips: +14%, +10%, +12%",
 holding: "Buy",
 risk: "High",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Speculative"
 },
 {
 id: 94,
 name: "George",
 avatar: "https://randomuser.me/api/portraits/men/94.jpg",
 asset_type: "Crypto",
 sector: "Technology",
 tip: "Cardano focuses on scalability.\nLong-term fundamentals are promising.",
 symbol: "ADAUSD",
 created_at: "2025-06-03T04:00:00Z",
 entry_price: 2.50,
 exit_price: 2.45,
 target_duration: "2 weeks",
 allocation: "3%",
 catalyst: "Network upgrades",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "MACD neutral",
 confidence: "Moderate",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "15%",
 performance: "Last 3 tips: +12%, +10%, +13%",
 holding: "Hold",
 risk: "High",
 conviction: "Medium",
 win_rate: "72%",
 strategy: "Growth"
 },
 {
 id: 95,
 name: "Hannah",
 avatar: "https://randomuser.me/api/portraits/women/95.jpg",
 asset_type: "Crypto",
 sector: "Technology",
 tip: "Solana shows growth in DeFi.\nNetwork usage drives its value.",
 symbol: "SOLUSD",
 created_at: "2025-06-02T05:00:00Z",
 entry_price: 100,
 exit_price: 110,
 target_duration: "3 weeks",
 allocation: "3%",
 catalyst: "DeFi adoption",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "RSI above 65",
 confidence: "High",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "15%",
 performance: "Last 3 tips: +12%, +10%, +14%",
 holding: "Buy",
 risk: "High",
 conviction: "Strong",
 win_rate: "75%",
 strategy: "Growth"
 },
 {
 id: 96,
 name: "Isaac",
 avatar: "https://randomuser.me/api/portraits/men/96.jpg",
 asset_type: "Crypto",
 sector: "Technology",
 tip: "Polkadot connects blockchains.\nDeveloper activity supports long-term value.",
 symbol: "DOTUSD",
 created_at: "2025-06-01T06:00:00Z",
 entry_price: 40,
 exit_price: 42,
 target_duration: "3 weeks",
 allocation: "3%",
 catalyst: "Network upgrades",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "MACD neutral",
 confidence: "Moderate",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "14%",
 performance: "Last 3 tips: +12%, +9%, +11%",
 holding: "Hold",
 risk: "High",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Growth"
 },
 {
 id: 97,
 name: "Julia",
 avatar: "https://randomuser.me/api/portraits/women/97.jpg",
 asset_type: "Crypto",
 sector: "Technology",
 tip: "Chainlink drives DeFi.\nData oracle demand fuels growth.",
 symbol: "LINKUSD",
 created_at: "2025-05-31T07:00:00Z",
 entry_price: 25,
 exit_price: 27,
 target_duration: "2 weeks",
 allocation: "3%",
 catalyst: "DeFi adoption",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "RSI above 60",
 confidence: "High",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "15%",
 performance: "Last 3 tips: +14%, +12%, +13%",
 holding: "Buy",
 risk: "High",
 conviction: "Strong",
 win_rate: "78%",
 strategy: "Growth"
 },
 {
 id: 98,
 name: "Kyle",
 avatar: "https://randomuser.me/api/portraits/men/98.jpg",
 asset_type: "Crypto",
 sector: "Technology",
 tip: "Filecoin is a storage solution.\nAdoption trends will drive value.",
 symbol: "FILUSD",
 created_at: "2025-05-30T08:00:00Z",
 entry_price: 130,
 exit_price: 120,
 target_duration: "3 weeks",
 allocation: "2%",
 catalyst: "Storage demand",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Bollinger Bands neutral",
 confidence: "Moderate",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "15%",
 performance: "Last 3 tips: +13%, +12%, +14%",
 holding: "Hold",
 risk: "High",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Growth"
 },
 {
 id: 99,
 name: "Laura",
 avatar: "https://randomuser.me/api/portraits/women/99.jpg",
 asset_type: "Crypto",
 sector: "Technology",
 tip: "Uniswap fuels DeFi.\nLiquidity demand supports growth.",
 symbol: "UNIUSD",
 created_at: "2025-05-29T09:00:00Z",
 entry_price: 25,
 exit_price: 30,
 target_duration: "2 weeks",
 allocation: "3%",
 catalyst: "DeFi usage",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "RSI above 70",
 confidence: "High",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "16%",
 performance: "Last 3 tips: +15%, +13%, +14%",
 holding: "Buy",
 risk: "High",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Growth"
 },
 {
 id: 100,
 name: "Michael",
 avatar: "https://randomuser.me/api/portraits/men/100.jpg",
 asset_type: "Crypto",
 sector: "Technology",
 tip: "Avalanche is fast and scalable.\nDeFi and NFT demand drive its value.",
 symbol: "AVAXUSD",
 created_at: "2025-05-28T10:00:00Z",
 entry_price: 90,
 exit_price: 95,
 target_duration: "2 weeks",
 allocation: "2%",
 catalyst: "DeFi and NFT",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "MACD bullish signal",
 confidence: "High",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "15%",
 performance: "Last 3 tips: +14%, +13%, +12%",
 holding: "Buy",
 risk: "High",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Growth"
 },
 {
 id: 101,
 name: "Alice",
 avatar: "https://randomuser.me/api/portraits/women/101.jpg",
 asset_type: "Crypto",
 sector: "Technology",
 tip: "Crypto XLMUSD sees volatility on Geopolitical event.\nAdoption trends drive long-term value.",
 symbol: "XLMUSD",
 created_at: "2025-04-16T14:00:00Z",
 entry_price: 362.86,
 exit_price: 340.35,
 target_duration: "3 days",
 allocation: "15%",
 catalyst: "Geopolitical event",
 valuation: "Undervalued",
 sentiment: "Neutral",
 technical: "RSI above 61",
 confidence: "Moderate",
 diversification: "Balances sector risk",
 liquidity: "Very High",
 expected_return: "15%",
 performance: "Last 3 tips: +7%, -5%, +9%",
 holding: "Hold",
 risk: "Low",
 conviction: "Weak",
 win_rate: "67%",
 strategy: "Dividend"
 }
];

export function timeAgo(dateString: string) {
  const now = new Date();
  const date = new Date(dateString);
  const diff = Math.floor((now.getTime() - date.getTime()) / 1000);
  if (diff >= 0) {
    if (diff < 60) return `${diff}s ago`;
    if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
    if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
    return `${Math.floor(diff / 86400)}d ago`;
  } else {
    // Future date
    const futureDiff = Math.abs(diff);
    if (futureDiff < 60) return `${futureDiff}s ago`;
    if (futureDiff < 3600) return `${Math.floor(futureDiff / 60)}m ago`;
    if (futureDiff < 86400) return `${Math.floor(futureDiff / 3600)}h ago`;
    return `${Math.floor(futureDiff / 86400)}d ago`;
  }
}


